config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqa-composer-templates:
      branch: feature/dynamic_tool_gathering
      repo: https://github.com/EOSC-synergy/sqa-composer-templates
environment: {}
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - curl localhost
        container: qc.fair_surly-cinnabar-dog
timeout: 600
